@startuml サラダを作る
    start
    :材料の確認;
    :野菜を洗う
    作業時間2分;
    :レタスを切る
        作業時間1分;
    :トマトを切る
        作業時間1分;
    :玉ねぎを切る
        作業時間1分;
    :さらに盛り付ける
        作業時間4分;
    :ドレッシングをかける
        作業時間1分;
    end
@enduml 