@startuml ステーキを作る
    start
    :材料の確認;
    fork
    :フライパンを温める
    作業時間1分;
    fork again
    :肉の筋を切る
        作業時間1分;
    :肉に塩コショウで下味をする
        作業時間1分;
    end merge
    :肉を焼く
    作業時間2分;
    :裏返して焼く
    作業時間2;
    end
@enduml 