@startuml スープを作る
    start
    :材料の確認;
    fork
    :お湯を作る
    作業時間5分;
    :お湯に鶏がらを入れる
    作業時間1分;
    fork again
    :卵を割る
        作業時間1分;
    :割った卵を混ぜる
        作業時間1分;
    end merge
    :卵を混ぜながら入れる;
    end
@enduml 