@startwbs デザート
title バナナヨーグルトを作る
* バナナヨーグルト
**[#SkyBlue] 買い出し
***[#Yellow] スーパーでヨーグルトを買う
***[#Yellow] スーパーでバナナを買う
**[#SkyBlue] バナナヨーグルトを作る
***[#Yellow] ヨーグルトを入れる
***[#Yellow] バナナを切る
***[#Yellow] ヨーグルトにバナナを入れる


@endwbs