@startuml dinner-project
    start
    :夕食内容を決める
    5分;
    :分担を決める
    3分;
    fork
    :・オウタ
    買い出し;
    :スーパーで材料を買う
    作業時間20分;
    fork again
    :・マサキ、キショウ
        調理準備;
    fork
    :・マサキ
    調理器具時の準備
    作業時間10分;        
    fork again
    :・キショウ
    米を炊く@startuml じゃんけんゲーム
    start
    :夕食内容を決める
    5分;
    :分担を決める
    3分;
        fork
        :・オウタ
        買い出し;
        :スーパーで材料を買う
        作業時間40分;
        fork again
        :・マサキ、キショウ
            調理準備;
            fork
            :・マサキ
            調理器具時の準備
            作業時間10分;        
            fork again
            :・キショウ
            米を炊く
            作業時間20分;
        end merge
        end merge
        :調理開始;
        fork
        :・マサキ
        ステーキを作る
        作業時間15分;
        fork again
            :・オウタ
            サラダを作る
            作業時間15分;        
        fork again
            :・キショウ
            スープを作る
            作業時間20分;
        fork again
            :マサキ
            デザートを作る
            作業時間5分;
        end fork
        :みんなでおいしく食べる;
        end
@enduml 